PetPhotos/urls.py
from django.urls import path
from PetPhotos import views

app_name = 'PetPhotos'

urlpatterns = [
    path('', views.index, name='index'),
    path('user_profiles/', views.user_profiles, name='user_profiles'),
    path('user_profile/<username>/', views.user_profile, name='user_profile'),
    path('categories/', views.categories, name='categories'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('add_pet/', views.add_pet, name='add_pet'),
    path('add_picture/', views.add_picture, name='add_picture'),
    path('view_pet_profile/<slug:pet_slug>/', views.view_pet_profile, name='view_pet_profile'),
    path('view_picture/<slug:id>/', views.view_picture, name='view_picture'),
    path('search_category/', views.search_category, name='search_category'),
    path('like/<slug:id>/', views.like_view, name='like_post'),
    path('delete/<slug:pic_id>/<slug:com_id>', views.del_comment, name='del_comment'),
    path('delete_pet/<slug:pet_id>/<slug:own_id>', views.del_pet, name='del_pet'),
    path('delete_pic/<slug:pic_id>/<slug:cat_id>', views.del_pic, name='del_pic'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('trending/', views.trending, name='trending')
]

pet_photos_team_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from PetPhotos import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
	path('PetPhotos/', include('PetPhotos.urls')), #Pass the handling of /PetPhotos/ urls to the urls.py file in the app folder
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PetPhotos/forms.py
from django import forms
from PetPhotos.models import Category, Pet, Picture, Comment
from django.contrib.auth.models import User
from django.utils import timezone


"""
    CategoryForm form creates a Category model instance, requesting the name of the category
"""


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name. Max 128 characters.", widget=forms.TextInput(attrs={'class': 'form-control', 
                                                    'placeholder': 'Category Name'}))
    creation_date = timezone.now()
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


"""
    PetForm form creates a Pet model instance, requesting the name of the pet and picture
"""


class PetForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the pet name. Max 128 characters.", widget=forms.TextInput(attrs={'class':'form-control', 
                                                        'placeholder': 'Pet Name'}))
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Pet
        fields = ('name', 'picture')
        widgets = {'picture': forms.FileInput(attrs={'class': 'btn btn-outline-secondary'})}


"""
    PictureForm form creates a Picture model instance, requesting the picture and the name of the category it will 
    belong to
"""


class PictureForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all().order_by('name'), label='Select Category', 
                    widget=forms.Select(attrs={'class': 'form-control', 'placeholder':'Category'}), help_text="Choose a Category")
    creation_date = timezone.now()

    class Meta:
        model = Picture
        fields = ('category', 'picture')
        widgets = {'picture': forms.FileInput(attrs={'class': 'btn btn-outline-secondary'})}


"""
    UserForm form creates a User model instance, requesting the username, email, and password
"""


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Password'}), label='')

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        widgets = {'username': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Username - 150 characters or fewer. Letters, digits and @/./+/-/_ only', 'aria-describedby':'usernameHelp'}),
                    'email': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Email Address', 'aria-describedby':'usernameHelp'})}
        labels = {'username': '', 'email': ''}
        help_texts = {'username': ''}


"""
    CommentForm form creates a Comment model instance, requesting the body of the comment
"""


class CommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'size': 80, 'class':'form-control', 'placeholder':'Comment'}),
                              help_text="Max 300 characters.")
    creation_date = timezone.now()

    class Meta:
        model = Comment
        fields = ('comment',)

PetPhotos/views.py
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from PetPhotos.models import Category, Picture, Pet, Comment
from PetPhotos.forms import CategoryForm, UserForm, PetForm, PictureForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Max

"""
    index view displays the "Home Page"
"""


def index(request):
    context_dict = {'results': Category.objects.all()}

    return render(request, 'PetPhotos/index.html', context=context_dict)


"""
    show_category view displays a category name and all the pictures related to that particular category
"""


def show_category(request, category_name_slug):
    context_dict = {'results': Category.objects.all()}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pictures = Picture.objects.filter(category=category)
        context_dict['pictures'] = pictures
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pictures'] = None

    return render(request, 'PetPhotos/category.html', context=context_dict)


"""
    categories view displays a list of alphabetically ordered categories
"""


def categories(request):
    context_dict = {'results': Category.objects.all(), 'categories': Category.objects.order_by('name')}

    return render(request, 'PetPhotos/categories.html', context=context_dict)


"""
    user_profiles view displays a list of alphabetically ordered user profiles
"""


def user_profiles(request):
    context_dict = {'results': Category.objects.all(), 'profiles': User.objects.order_by('username')}

    return render(request, 'PetPhotos/user_profiles.html', context=context_dict)


"""
    user_profile view shows a profile of a particular user
"""


def user_profile(request, username):
    context_dict = {'results': Category.objects.all()}

    try:
        user = User.objects.get(username=username)
        pets = Pet.objects.filter(owner=User.objects.get(username=user.username))
        context_dict['u'] = user
        context_dict['pets'] = pets

    except User.DoesNotExist:
        context_dict['u'] = None
        context_dict['pets'] = None

    return render(request, 'PetPhotos/user_profile.html', context=context_dict)


"""
    view_pet_profile view serves as a page to view a pet profile of a particular user
"""


def view_pet_profile(request, pet_slug):
    context_dict = {'results': Category.objects.all()}

    try:
        context_dict['pet'] = Pet.objects.get(slug=pet_slug)

    except Pet.DoesNotExist:
        context_dict['pet'] = None

    return render(request, 'PetPhotos/view_pet_profile.html', context=context_dict)


"""
    add_category view serves as a page where user can add a category
"""


@login_required
def add_category(request):
    context_dict = {'results': Category.objects.all()}

    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        name = request.POST.get('name').capitalize()

        if Category.objects.filter(name=name).exists():
            c = Category.objects.get(name=name)
            return HttpResponseRedirect(reverse('PetPhotos:show_category', args=[str(c.slug)]))

        if form.is_valid():
            form.save(commit=True)
            return redirect('PetPhotos:index')

        else:
            print(form.errors)

    context_dict['form'] = form

    return render(request, 'PetPhotos/add_category.html', context=context_dict)


"""
    register view serves as a page where user can register
"""


def register(request):
    context_dict = {'results': Category.objects.all()}

    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            login(request, user)
            return redirect(reverse('PetPhotos:index'))
        else:
            print(user_form.errors)

    else:
        user_form = UserForm()

    context_dict['user_form'] = user_form

    return render(request, 'PetPhotos/register.html', context=context_dict)


"""
    user_login view serves as a page where user can log in
"""


def user_login(request):
    context_dict = {'results': Category.objects.all()}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:
                login(request, user)
                return redirect(reverse('PetPhotos:index'))

            else:
                return HttpResponse("Your account is disabled!")

        else:
            print("Invalid username or password. Please check the details again!")
            return HttpResponse("Invalid details entered.")

    else:
        return render(request, 'PetPhotos/login.html', context=context_dict)


"""
    add_pet view is a page where you can as an owner add a pet to your collection of pets and the reference to 
    the owner for the owner field in the Pet model is essentially a request for the logged-in user
"""


@login_required
def add_pet(request):
    context_dict = {'results': Category.objects.all()}

    form = PetForm()

    if request.method == 'POST':
        form = PetForm(request.POST, request.FILES)

        name = request.POST.get('name')
        owner = request.user

        if Pet.objects.filter(name=name, owner=owner).exists():
            p = Pet.objects.get(name=name, owner=owner)
            return HttpResponseRedirect(reverse('PetPhotos:view_pet_profile', args=[str(p.slug)]))

        if form.is_valid():
            pet = form.save(commit=False)
            pet.owner = request.user

            if 'picture' in request.FILES:
                pet.picture = request.FILES['picture']

            pet.save()
            return HttpResponseRedirect(reverse('PetPhotos:view_pet_profile', args=[str(pet.slug)]))

        else:
            print(form.errors)

    context_dict['form'] = form
    return render(request, 'PetPhotos/add_pet.html', context=context_dict)


"""
    add_picture view is a page where you can add an animal picture to a particular category and the reference to 
    the creator for the creator field in the Picture model is essentially a request for the logged-in user
"""


@login_required
def add_picture(request):
    context_dict = {'results': Category.objects.all()}

    form = PictureForm()

    if request.method == 'POST':
        form = PictureForm(request.POST, request.FILES)

        if form.is_valid():
            picture = form.save(commit=False)
            picture.creator = request.user

            if 'picture' in request.FILES:
                picture.picture = request.FILES['picture']

            picture.save()
            return redirect('PetPhotos:index')

        else:
            print(form.errors)

    context_dict['form'] = form
    return render(request, 'PetPhotos/add_picture.html', context=context_dict)


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('PetPhotos:index'))
  

"""
    view_picture view is a page where you can see a particular animal from a particular category, its comments, like 
    button, and has a part (form) where a logged in user can add a comment
"""


def view_picture(request, id):
    context_dict = {'results': Category.objects.all()}

    try:
        picture = Picture.objects.get(id=id)
        liked = False

        if picture.likes.filter(id=request.user.id).exists():
            liked = True

        if request.method == 'POST':
            form = CommentForm(request.POST or None)

            if form.is_valid():
                comment = form.save(commit=False)
                comment.creator = request.user
                comment.picture = picture
                comment.comment = request.POST.get('comment')
                comment.save()
                return HttpResponseRedirect(reverse('PetPhotos:view_picture', args=[str(id)]))

        else:
            comment_form = CommentForm()

        context_dict['comment_form'] = comment_form
        context_dict['picture'] = picture
        context_dict['likes'] = picture.number_of_likes()
        context_dict['liked'] = liked
        context_dict['comments'] = Comment.objects.filter(picture=picture).order_by('-id')

    except Picture.DoesNotExist:
        context_dict['picture'] = None
        context_dict['comment_form'] = None
        context_dict['picture'] = None
        context_dict['likes'] = None
        context_dict['liked'] = None
        context_dict['comments'] = None

    return render(request, 'PetPhotos/view_picture.html', context=context_dict)


"""
    search_category view takes as an input the searched string from the search bar and displays all the categories that 
    contain the string anywhere. For instance, if we search for "sh" the list would display "shellfish" as well as 
    "jellyfish" if they both were in the category list.
"""


def search_category(request):
    context_dict = {'results': Category.objects.all()}

    if request.method == "POST":
        searched = request.POST.get('searched')
        context_dict['searched'] = searched
        context_dict['categories_sug'] = Category.objects.filter(name__contains=searched)
        return render(request, 'PetPhotos/search_category.html', context=context_dict)

    else:
        return render(request, 'PetPhotos/search_category.html', context=context_dict)


"""
    trending view displays 6 most liked pictures, 6 most recent pictures, and 5 most recent categories
"""


def trending(request):

templates/PetPhotos/add_pet.html
<!-- Page where user can add a pet to his profile -->

{{% extends 'PetPhotos/base.html' %}

{% block title_block %}
    Add a Pet
{% endblock %}

{% block body_block %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-3">Add a Pet</h1>
      <p class="lead">Add a new pet to your profile</p>
    </div>
</div>
<hr>
    <div class="textform">
        
        <form id="category_form" method="post" action="{% url 'PetPhotos:add_pet' %}" enctype="multipart/form-data">

            {% csrf_token %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Add Pet" class="btn btn-success" />
        </form>
    </div>
{% endblock %}

templates/PetPhotos/add_picture.html
<!-- Page where user can add a picture to a category -->

{{% extends 'PetPhotos/base.html' %}

{% block title_block %}
    Add a Picture
{% endblock %}


{% block body_block %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
        <h1 class="display-3">Add a Picture</h1>
        <p class="lead">Add a new picture to a category</p>
        </div>
    </div>
    <hr>
    <div class="textform">
        <form id="category_form" method="post" action="{% url 'PetPhotos:add_picture' %}"enctype="multipart/form-data" >

            {% csrf_token %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Add Picture" class="btn btn-success"/>
        </form>
    </div>
{% endblock %}

templates/PetPhotos/addpet.html
<!DOCTYPE html>
{% extends PetPhotos/base.html}
{% load staticfiles %}

<html>
    {% block title_block %}
    Add a New Pet
    {% endblock %}

    {% block body_block %}
    <h1>Add a New Pet</h1>
    <div>
        <form id="PetForm" method="POST" action="/PetPhotos/addpet/">
        {% csrf_token %}
        {% for field in form.hidden_fields %}
            {{hidden}}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{field.errors}}
            {{field.help_text}}
            {{field}}
        {% endfor %}
        <input type="submit" name = "submit" value="Create Category" />
        </form>
    </div>
    {% endblock %}
</html>

templates/PetPhotos/base.html
<!DOCTYPE html>
{% load static %}
{% load pp_template_tags %}

<!-- BOOTSTRAP -->
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Jekyll v3.8.5">
        <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
        <title>
            PetPhotos - {% block title_block %}
            A Place to Share Pets!
            {% endblock %}
        </title>

        <!-- Bootstrap core CSS -->
        <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

        <!-- Custom styles for this template -->
        <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">

    </head>
    
    <body>
        <script src="{% static 'js/hovereffects.js' %}"></script>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'index' %}">PetPhotos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- MENU -->

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>

                        <li class="nav-item"><a class="nav-link" href="{% url 'PetPhotos:categories' %}">Categories</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'PetPhotos:user_profiles' %}">Profiles</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'PetPhotos:trending' %}">Trending</a></li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'PetPhotos:add_category' %}">Add Category</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'PetPhotos:add_pet' %}">Add Pet</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'PetPhotos:add_picture' %}">Add Picture</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'PetPhotos:logout' %}">Log Out</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'PetPhotos:login' %}">Log In</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'PetPhotos:register' %}">Register</a></li>
                        {% endif %}
                    </ul>


                    <!-- SEARCH BAR -->

                    <div class="float-xl-right">

                        <form class="d-flex" id="d-flex" method=POST action="{% url 'PetPhotos:search_category' %}">
                            {% csrf_token %}
                            <input class="form-control mr-sm-2" id="tags" type="search" list="categorylist" placeholder="Search Categories" name="searched">
                            <datalist id="categorylist">
                                {% for res in results %}
                                    <option value="{{ res.name }}"></option>
                                {% endfor %}
                            </datalist>

                            <button class="btn btn-outline-success" id="search_b" type="submit">Search</button>

                        </form></div>
                </div>
            </nav>
        </header>


        <!--SIDEBAR-->

        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                    <div class="centred categorybuttons" style="vertical-align: center;">
                        {% if user.is_authenticated %}
                        <p class="sidebartext">Logged in as {{user.username}}</p>
                        <a href="{% url 'PetPhotos:user_profile' user.username %}" class="btn btn-outline-secondary btn-block">My Profile</a>
                        {% else %}
                        <p class="authindicator">Not logged in<p>
                        {% endif %}
                    </div><hr>
                    <p class="centred sidebartext">All Categories</p>
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>

                <main role="main" id="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% block body_block %}{% endblock %}
                </main>
                    <!-- FOOTER -->
                    <footer class="footer">
                        <hr>
                        <p id="up_bit" class="float-right"><a href="#">Back to top</a></p>
                        <p id="up_bit_too" class="float-right">&copy; 2021 WAD2 Team 5F &middot;</p>
                    </footer>

            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>

    </body>

</html>

templates/PetPhotos/categories.html
<!-- Page that displays a list of all current categories in alphabetical order -->

{% extends 'PetPhotos/base.html' %}
{% load static %}

{% block title_block %}
    Categories
{% endblock %}

{% block body_block %}
    {% if categories %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-3">All Categories</h1>
        </div>
    </div>
        <hr>
        <div class="container-fluid">
            <div class= "row">
            {% for c in categories %}
            <div class="col">
                <div class="card border-primary">
                    <div class="card-body">
                      <h5 class="card-title">{{c.name}}</h5>
                      <a href="{% url 'PetPhotos:show_category' c.slug %}" class="btn btn-outline-primary">View</a>
                    </div>
                  </div>
            </div>
            {% endfor %}
        </div></div>
    {% else %}
        No category exists.
    {% endif %}
{% endblock %}

templates/PetPhotos/category.html
<!-- Page where is the category with all the related pictures displayed, alongside with sidebar of all categories -->

{% extends 'PetPhotos/base.html' %}
{% load static %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-3">{{category.name}}</h1>
        </div>
    </div>
        <hr>
        <div>
            {% if pictures %}

                {% for picture in pictures %}
                    <a href="{% url 'PetPhotos:view_picture' picture.id %}"><img src="{{ picture.picture.url }}" alt="img" class="smallimg" onmouseenter="hoverer(this)" onmouseleave="dehoverer(this)"></a>
                {% endfor %}

            {% else %}
                <strong>No pictures currently in category.</strong>
            {% endif %}
        </div>

    {% else %}
        This category doesn't exist.
    {% endif %}
{% endblock %}

templates/PetPhotos/index.html
<!-- Home Page -->

{% extends 'PetPhotos/base.html' %}
{% load static %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}
    <div class="centred">
        <h1> Welcome to PetPhotos</h1>
        <h5>Share your pets with the world!</h5>
        <img class="indeximg img-fluid"
        src="{% static 'images/petphotos.jpg'%}" alt="An image of several pets including dogs, cats and a rabbit" />
    </div>

    <div style="text-align: center;">
        <img src="{% static 'images/pplogo2.png'%}" alt="PetPhotos Logo" class="logo"/>
    </div>

    <hr>

    <div class="centred">
        {% if user.is_authenticated %}
            <strong>Welcome back {{user.username}}</strong>
        {% else %}
            <strong>You're not logged in. <a href="{% url 'PetPhotos:login' %}">Log In</a> or <a href="{% url 'PetPhotos:register' %}">Register</a> <!--SIGN UP--></strong>

        {% endif %}
    </div>
{% endblock %}

templates/PetPhotos/login.html
<!-- Login Page -->

{% extends 'PetPhotos/base.html' %}
{% load static %}


{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-3">Login to PetPhotos</h1>
    </div>
</div>
    <hr>
    <div>
    <div>
        <form id="login_form" method="post" action="{% url 'PetPhotos:login' %}">

        {% csrf_token %}

        <div class="textForm">
        <input type="text" placeholder="Username"name="username" value="" size="50" class="form-control"/>
        <br />
        <input type="password" placeholder="Password" name="password" value="" size="50" class="form-control" /> <br />

        <input class="btn btn-success " type="submit" value="Submit" />
    </div>
        </form>
    </div>
</div>
{% endblock %}

templates/PetPhotos/register.html
<!-- Register Page -->

{% extends 'PetPhotos/base.html' %}
{% load static %}


{% block title_block %}
    Register
{% endblock %}

{% block body_block %}

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-3">Register for PetPhotos</h1>
        </div>
    </div>
    <div class="centred">
    <hr>
    <div class="textForm">
        <h3>Please register here.</h3><br />
        <form id="user_form" method="post" action="{% url 'PetPhotos:register' %}" enctype = "multipart/form-data">

            {% csrf_token %}

            {{ user_form.as_p}}
            {{ profile_form.as_p }}
            <input type="submit" name="submit" value="Register" class="btn btn-success" />
        </form>
    </div>
</div>
{% endblock %}

templates/PetPhotos/user_profiles.html
<!-- Page that displays a list of all current categories in alphabetical order -->

{% extends 'PetPhotos/base.html' %}
{% load static %}

{% block title_block %}
    Profiles
{% endblock %}

{% block body_block %}
    {% if profiles %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">User Profiles</h1>
        </div>
    </div>
        <hr>
        <div>
            <div class="container.fluid">
                <div class="row justify-content-start">
                {% for p in profiles %}
                    <div class="col" style="padding: 10px;">
                    <div class="card" style="width: 18rem;">
                    <div class="card-body">
                    <h5 class="card-title">{{p.username}}</h5>
                    <a class= "btn btn-outline-primary btn-block" href="{% url 'PetPhotos:user_profile' p.username %}">View Pets</a>
                    </div> </div></div>
                {% endfor %}
            </div></div>
        </div>
    {% else %}
        No user exists.
    {% endif %}
{% endblock %}

templates/PetPhotos/view_pet_profile.html
<!-- Page that displays an animal of a certain user -->

{% extends 'PetPhotos/base.html' %}

{% block title_block %}
    {% if pet %}
        {{pet.name}}
    {% else %}
        Unknown Pet
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if pet %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">Pet Profile</h1>
        </div>
    </div>
    <hr>
    <div class="container-fluid">
        <h4>Name: {{ pet.name }}</h4>
        <p><b>Owner:</b> <a href="{% url 'PetPhotos:user_profile' pet.owner %}">{{ pet.owner }}</a></p>
        <hr>
        <img src="{{ pet.picture.url }}" alt="img" class="img-fluid view_pic">
    </div>
    {% if user.id == pet.owner.id %}
        <form action="{% url 'PetPhotos:del_pet' pet.slug pet.owner.username %}" method="POST">
            {% csrf_token %}

             <button type="submit" name="delete" own_id ="{{ pet.owner.username }}" pet_id ="{{ pet.slug }}" class="btn btn-outline-dark">Delete</button>

        </form>
    {% endif %}
    {% else %}
        This pet doesn't exist.
    {% endif %}
{% endblock %}